title = "Einara Zahn"
baseURL = "https://einaraz.github.io/"
theme = "ananke"
resourceDir = "../resources"

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true

[services.disqus]
  shortname = 'YOURSHORTNAME'
  
[services.googleAnalytics]
id = ''

[[menu.main]]
  name = "Resources"
  url = "/resources/"
  weight = 40

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 10

[[menu.main]]
  name = "Publications"
  url = "/publications/"
  weight = 30

[[menu.main]]
  name = "Research"
  url = "/research/"
  weight = 20

[pagination]
pagerSize = 3 # this is set low for demonstrating with dummy content. Set to a higher number

[languages.en]
contentDir = "content/en"
languageCode = 'en-US'
weight = 1
title = ""
# languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
mainSections = ["post"]
text_color = ""
author = "Einara Zahn" # default author, override via `author` in a posts front matter
favicon = ""
omit_header_text = true
# site_logo = "images/TigerUrbanClimate.webp"
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-navy"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-60"
recent_posts_number = 3
commentoEnable = true
custom_css = ["custom.css"]


[params.ananke.social.share]
networks = [
  "linkedin",
  "scholar",
]

[params.ananke.social.follow]
networks = [
  "linkedin",
  "github",
]

###[params.ananke.social.facebook]
###username = "patrick.kollitsch"
#### profilelink = "https://www.facebook.com/patrick.kollitsch"

[params.ananke.social.linkedin]
username = "Einara Zahn"
profilelink = "https://www.linkedin.com/in/einara-z-3128362ba/"

[params.ananke.social.github]
username = "Einara Zahn"
profilelink = "https://github.com/einaraz"